# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e01d0d2490583abb71e78975f8c5c059053765d2dc254efc4e7923d8398854eb64b2cadff85fe8108c92dc168b80cd6c76b1857c090bf5391d324ccfa3786f

test:
  secret_key_base: 5de461b38d5c9fd89ab715988b459e26c51b1f31e78a37863ea9bd456270dcdde22ccee33aa8ca2ac66b4f2f73a2fdd60e0ca1a6c11f0f40895173827fbd0722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
